version: 0.1
log:
  accesslog:
    disabled: false
  level: {{ if eq (env "PLATFORM_BRANCH") "master" }}info{{ else }}debug{{ end }}
  formatter: text
  fields:
    branch: {{ env "PLATFORM_BRANCH" }}
    environment: {{ env "PLATFORM_ENVIRONMENT" }}
    project: {{ env "PLATFORM_PROJECT" }}
    service: {{ env "PLATFORM_APPLICATION_NAME" }}
    tree_id: {{ env "PLATFORM_TREE_ID" }}
storage:
  filesystem:
    rootdirectory: {{ env "PLATFORM_DIR" }}/var/lib/registry
auth:
  token:
    realm: {{ .TokenURL }}auth
    service: Docker Registry
    issuer: Acme Auth Server
    rootcertbundle: {{ env "PLATFORM_DIR" }}/bundle.crt
http:
  addr: localhost:{{ env "PORT" }}
  net: tcp
  prefix: /
  host: {{ .RegistryURL }}
  secret: {{ env "PLATFORM_PROJECT_ENTROPY" }}
redis:
  addr: {{ rel "cache.[0].host" }}:{{ rel "cache.[0].port" }}
  db: 0
{{ with rel "cache.[0].password" }}  password: {{ . }}{{ end }}
