server:
  addr: :{{ env "PORT" }}
token:
  issuer: "Acme Auth Server"
  expiration: 900
  certificate: {{ env "PLATFORM_DIR" }}/server.crt
  key: /tmp/server.key

users:
{{ range $name, $password := (var "users") }}
  "{{ $name }}":
    password: {{ bcrypt $password }}
{{ end }}
acl:
  - match: {ip: "127.0.0.0/8"}
    actions: ["*"]
    comment: Allow everything from localhost (IPv4)
  - match: {ip: "::1"}
    actions: ["*"]
    comment: Allow everything from localhost (IPv6)
  - match: {account: "admin"}
    actions: ["*"]
    comment: Admin has full access to everything
  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["*"]
    comment: Logged in users have full access to images that are in their namespace
  - match: {account: "/.+", type: "registry", name: "catalog"}
    actions: ["*"]
    comments: Logged in users can query the catalog.
  - match: {name: "${labels:project}/*"}
    actions: ["push", "pull"]
    comment: Users can push to any project they are assigned to
# access is denied by default
