# The routes of the project.
#
# Each route describes how an incoming URL is going to be processed by Platform.sh.
#
# See https://docs.platform.sh/user_guide/reference/routes-yaml.html

https://{all}/:
  type: upstream
  upstream: app:http

https://{default}/auth:
  type: upstream
  upstream: auth:http

https://{all}/v2/:
  type: upstream
  upstream: registry:http
