# The services of the project.
#
# Each service listed will be deployed in its own container as part of your
# Platform.sh project.
#
# See https://docs.platform.sh/user_guide/reference/services-yaml.html

rediscache:
  type: redis:5.0

files:
  type: network-storage:1.0
  disk: 4992
